apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ../observability
  - ingress.yaml
  - traefik-rate-limit.yaml

namespace: peak-booking

patches:
  - path: app-loadtest-patch.yaml
  - path: config-loadtest-patch.yaml

images:
  - name: peak-booking/backend
    newTag: loadtest
