apiVersion: v1
kind: Secret
metadata:
  name: booking-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: peak
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_DATABASE: peak_booking
  MYSQL_USER: peak
  MYSQL_PASSWORD: peak
  MYSQL_ROOT_PASSWORD: root
