apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - lgtm.yaml

namespace: peak-booking

configMapGenerator:
  - name: lgtm-prometheus-config
    files:
      - prometheus.yaml=prometheus.yaml
  - name: lgtm-grafana-dashboard-provider
    files:
      - custom.yaml=custom.yaml
  - name: lgtm-grafana-dashboards
    files:
      - peak-booking-loadtest-dashboard.json=peak-booking-loadtest-dashboard.json
      - peak-booking-bottleneck-dashboard.json=dashboards/peak-booking-bottleneck-dashboard.json
      - mysql-exporter-dashboard.json=dashboards/mysql-exporter-dashboard.json
      - redis-exporter-dashboard.json=dashboards/redis-exporter-dashboard.json

generatorOptions:
  disableNameSuffixHash: true
