global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: peak-booking-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - booking-service:8080
        labels:
          application: peak-booking-service
